# Generated by Django 4.2.4 on 2024-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
