# Generated by Django 4.2.4 on 2024-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_information_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
