# Generated by Django 4.2.4 on 2024-03-22 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_information_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Joined'),
            preserve_default=False,
        ),
    ]
