# Generated by Django 4.2.4 on 2024-04-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_information_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_information',
            name='date_joined',
        ),
    ]
