# Generated by Django 4.2.4 on 2024-03-22 09:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_list',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
