# Generated by Django 4.2.4 on 2024-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_alter_contact_list_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_list',
            name='name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
