# Generated by Django 4.2.4 on 2024-03-22 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_list', '0003_alter_contact_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_list',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
